/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-02-14 05:37:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class member_005fwrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/member/../include/navbar.jsp", Long.valueOf(1675829143388L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<form name=\"myform\" id=\"myform\">\r\n");
      out.write("		<input type=\"hidden\" name=\"idcheck\" id=\"idcheck\" value=\"N\">\r\n");
      out.write("		<!-- 메뉴 -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<!-- 메뉴 -->\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<!-- 한글 깨짐 방지 -->\r\n");

// 공통변수 CONTEXT 만들어 놓고 갖다 쓰기
String CONTEXT = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-sm navbar-light\" style=\"background-color: lavender\">\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<a class=\"navbar-brand\" href=\"");
      out.print(CONTEXT);
      out.write("\"> <img\r\n");
      out.write("			src=\"https://imjustcreative.com/wp-content/uploads/2015/11/Screenshot-2019-11-23-17.32.44.jpg\" alt=\"Avatar Logo\"\r\n");
      out.write("			style=\"width: 40px;\" class=\"rounded-pill\">\r\n");
      out.write("		</a>\r\n");
      out.write("\r\n");
      out.write("		<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("			data-bs-target=\"#collapsibleNavbar\">\r\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("		</button>\r\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"collapsibleNavbar\">\r\n");
      out.write("			<ul class=\"navbar-nav\">\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("					href=\"");
      out.print(CONTEXT);
      out.write("/board/list?pg=0\">List</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("					href=\"");
      out.print(CONTEXT);
      out.write("/board/write\">Write</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("					href=\"");
      out.print(CONTEXT);
      out.write("/member/write\">Sign up</a></li>\r\n");
      out.write("				<li class=\"nav-item dropdown\"><a\r\n");
      out.write("					class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\"\r\n");
      out.write("					data-bs-toggle=\"dropdown\">Gallery</a>\r\n");
      out.write("					<ul class=\"dropdown-menu\">\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"");
      out.print(CONTEXT);
      out.write("/gallery/list\">Gallery list</a></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"");
      out.print(CONTEXT);
      out.write("/gallery/write\">Gallery write</a></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"#\">A third link</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		");
if(session.getAttribute("user_id")==null||session.getAttribute("user_id").equals("")) {
      out.write("\r\n");
      out.write("			<ul class=\"navbar-nav justify-content-end\">\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("				<a class=\"nav-link\" href=\"");
      out.print(CONTEXT);
      out.write("/member/login\">로그인</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("				<a class=\"nav-link\" href=\"");
      out.print(CONTEXT);
      out.write("/member/write\">회원가입</a>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		");
} else {
      out.write("\r\n");
      out.write("			<ul class=\"navbar-nav justify-content-end\">\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("				<a class=\"nav-link\" href=\"#none\">");
      out.print(session.getAttribute("user_name") );
      out.write("</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("				<a class=\"nav-link\" href=\"#none\" onclick=\"goLogout()\">로그아웃</a>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		");
} 
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function goLogout() {\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url:\"");
      out.print(request.getContextPath());
      out.write("/member/logout\",\r\n");
      out.write("		method:\"POST\",\r\n");
      out.write("		dataType:\"JSON\"\r\n");
      out.write("	})\r\n");
      out.write("	.done(function (response){\r\n");
      out.write("		alert(response.message);\r\n");
      out.write("		if(response.result==\"success\"){\r\n");
      out.write("			location.href=\"");
      out.print(request.getContextPath());
      out.write("/\";\r\n");
      out.write("		}\r\n");
      out.write("	})\r\n");
      out.write("	.fail((response, status, error)=>{\r\n");
      out.write("		console.log(error);\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"container mt-3\">\r\n");
      out.write("			<h3>Navbar With Dropdown</h3>\r\n");
      out.write("			<p>This example adds a dropdown menu in the navbar.</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<table class=\"table\">\r\n");
      out.write("				<colgroup>\r\n");
      out.write("					<col width=\"30%\">\r\n");
      out.write("					<col width=\"*\">\r\n");
      out.write("				</colgroup>\r\n");
      out.write("				<tbody>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>아이디</th>\r\n");
      out.write("						<td>\r\n");
      out.write("							<div class=\"input-group\">\r\n");
      out.write("								<input type=\"text\" class=\"form-control\" placeholder=\"아이디를 입력하세요\" name=\"user_id\" id=\"user_id\"> \r\n");
      out.write("									<button type=\"button\" class=\"btn\" style=\"background-color: lavender\" id=\"btnIdcheck\">아이디중복체크</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>패스워드</th>\r\n");
      out.write("						<td>\r\n");
      out.write("							<div class=\"input-group\">\r\n");
      out.write("								<input type=\"password\" class=\"form-control\" placeholder=\"패스워드를 입력하세요\" name=\"password\" id=\"password\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>패스워드확인</th>\r\n");
      out.write("						<td>\r\n");
      out.write("							<div class=\"input-group\">\r\n");
      out.write("								<input type=\"password\" class=\"form-control\" placeholder=\"패스워드를 입력하세요\" name=\"password2\" id=\"password2\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>이름</th>\r\n");
      out.write("						<td>\r\n");
      out.write("							<div class=\"input-group\">\r\n");
      out.write("								<input type=\"text\" class=\"form-control\" placeholder=\"이름을 입력하세요\" name=\"user_name\" id=\"user_name\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>닉네임</th>\r\n");
      out.write("						<td>\r\n");
      out.write("							<div class=\"input-group\">\r\n");
      out.write("								<input type=\"text\" class=\"form-control\" placeholder=\"닉네임을 입력하세요\" name=\"nickname\" id=\"nickname\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>이메일</th>\r\n");
      out.write("						<td>\r\n");
      out.write("							<div class=\"input-group\">\r\n");
      out.write("								<input type=\"email\" class=\"form-control\" placeholder=\"이메일을 입력하세요\" name=\"email\" id=\"email\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>전화번호</th>\r\n");
      out.write("						<td>\r\n");
      out.write("							<div class=\"input-group\">\r\n");
      out.write("								<input type=\"tel\" class=\"form-control\" placeholder=\"전화번호를 입력하세요\" name=\"phone\" id=\"phone\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>우편번호</th>\r\n");
      out.write("						<td>\r\n");
      out.write("					<div class=\"input-group\">\r\n");
      out.write("						<input type=\"text\" class=\"form-control\" name=\"zipcode\" id=\"sample4_postcode\" placeholder=\"우편번호\">\r\n");
      out.write("						<input type=\"button\" class=\"btn\" style=\"background-color: lavender\" onclick=\"sample4_execDaumPostcode()\" value=\"우편번호 찾기\">\r\n");
      out.write("					</div>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("						\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>주소</th>\r\n");
      out.write("						<td>\r\n");
      out.write("					<div class=\"input-group\">\r\n");
      out.write("						<input type=\"text\" class=\"form-control\" name=\"address1\" id=\"sample4_roadAddress\" placeholder=\"도로명주소\">\r\n");
      out.write("						<input type=\"text\" class=\"form-control\" id=\"sample4_jibunAddress\" placeholder=\"지번주소\">\r\n");
      out.write("						<span id=\"guide\" style=\"color:#999;display:none\"></span>\r\n");
      out.write("					</div>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>상세 주소</th>\r\n");
      out.write("						<td>\r\n");
      out.write("					<div class=\"input-group\">\r\n");
      out.write("						<input type=\"text\" class=\"form-control\" name=\"address2\" id=\"sample4_detailAddress\" placeholder=\"상세주소\">\r\n");
      out.write("						<input type=\"hidden\" class=\"form-control\" id=\"sample4_extraAddress\" placeholder=\"참고항목\">\r\n");
      out.write("					</div>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"container\" style=\"text-align: right\">\r\n");
      out.write("			<button type=\"button\" class=\"btn\" style=\"background-color: lavender\" id=\"btnSave\">등록</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    //본 예제에서는 도로명 주소 표기 방식에 대한 법령에 따라, 내려오는 데이터를 조합하여 올바른 주소를 구성하는 방법을 설명합니다.\r\n");
      out.write("    function sample4_execDaumPostcode() {\r\n");
      out.write("        new daum.Postcode({\r\n");
      out.write("            oncomplete: function(data) {\r\n");
      out.write("                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("                // 도로명 주소의 노출 규칙에 따라 주소를 표시한다.\r\n");
      out.write("                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                var roadAddr = data.roadAddress; // 도로명 주소 변수\r\n");
      out.write("                var extraRoadAddr = ''; // 참고 항목 변수\r\n");
      out.write("\r\n");
      out.write("                // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("                // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("                if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("                    extraRoadAddr += data.bname;\r\n");
      out.write("                }\r\n");
      out.write("                // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("                if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("                   extraRoadAddr += (extraRoadAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                }\r\n");
      out.write("                // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("                if(extraRoadAddr !== ''){\r\n");
      out.write("                    extraRoadAddr = ' (' + extraRoadAddr + ')';\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                document.getElementById('sample4_postcode').value = data.zonecode;\r\n");
      out.write("                document.getElementById(\"sample4_roadAddress\").value = roadAddr;\r\n");
      out.write("                document.getElementById(\"sample4_jibunAddress\").value = data.jibunAddress;\r\n");
      out.write("                \r\n");
      out.write("                // 참고항목 문자열이 있을 경우 해당 필드에 넣는다.\r\n");
      out.write("                if(roadAddr !== ''){\r\n");
      out.write("                    document.getElementById(\"sample4_extraAddress\").value = extraRoadAddr;\r\n");
      out.write("                } else {\r\n");
      out.write("                    document.getElementById(\"sample4_extraAddress\").value = '';\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                var guideTextBox = document.getElementById(\"guide\");\r\n");
      out.write("                // 사용자가 '선택 안함'을 클릭한 경우, 예상 주소라는 표시를 해준다.\r\n");
      out.write("                if(data.autoRoadAddress) {\r\n");
      out.write("                    var expRoadAddr = data.autoRoadAddress + extraRoadAddr;\r\n");
      out.write("                    guideTextBox.innerHTML = '(예상 도로명 주소 : ' + expRoadAddr + ')';\r\n");
      out.write("                    guideTextBox.style.display = 'block';\r\n");
      out.write("\r\n");
      out.write("                } else if(data.autoJibunAddress) {\r\n");
      out.write("                    var expJibunAddr = data.autoJibunAddress;\r\n");
      out.write("                    guideTextBox.innerHTML = '(예상 지번 주소 : ' + expJibunAddr + ')';\r\n");
      out.write("                    guideTextBox.style.display = 'block';\r\n");
      out.write("                } else {\r\n");
      out.write("                    guideTextBox.innerHTML = '';\r\n");
      out.write("                    guideTextBox.style.display = 'none';\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }).open();\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    $(()=>{\r\n");
      out.write("    	\r\n");
      out.write("    	$(\"#btnSave\").click(()=>{\r\n");
      out.write("    		if(!fnErrorCheck()){\r\n");
      out.write("    			return false; \r\n");
      out.write("    		}\r\n");
      out.write("    		\r\n");
      out.write("    		let data = $(\"#myform\").serialize();\r\n");
      out.write("    		$.ajax({\r\n");
      out.write("    			url:\"");
      out.print(request.getContextPath());
      out.write("/member/save\",\r\n");
      out.write("    			data:data,\r\n");
      out.write("    			type:\"POST\",\r\n");
      out.write("    			dataType:\"JSON\"\r\n");
      out.write("    		})\r\n");
      out.write("    		.done((res)=>{\r\n");
      out.write("    			alert(res.message);\r\n");
      out.write("    			if(res.result==\"success\"){\r\n");
      out.write("    				location.href=\"");
      out.print(request.getContextPath());
      out.write("/\";\r\n");
      out.write("    			}\r\n");
      out.write("    		})\r\n");
      out.write("    		.fail((res, status, error)=>{\r\n");
      out.write("    			console.log(status);\r\n");
      out.write("    			console.log(error);\r\n");
      out.write("    		})\r\n");
      out.write("    		\r\n");
      out.write("    	})\r\n");
      out.write("    	\r\n");
      out.write("    	\r\n");
      out.write("    	\r\n");
      out.write("    	$(\"#btnIdcheck\").click(()=>{\r\n");
      out.write("    		let user_id = $(\"#user_id\").val().trim();\r\n");
      out.write("    		\r\n");
      out.write("    		if($(\"#user_id\").val().trim().length<6)\r\n");
      out.write("			{\r\n");
      out.write("				alert(\"아이디는 6자리 이상이어야 합니다.\");\r\n");
      out.write("				return false; //함수 종료 \r\n");
      out.write("			}\r\n");
      out.write("    		\r\n");
      out.write("    		$.ajax({\r\n");
      out.write("    			url:\"");
      out.print(request.getContextPath());
      out.write("/member/idcheck\",\r\n");
      out.write("    			data: {\"user_id\":user_id},\r\n");
      out.write("    			method: \"POST\",\r\n");
      out.write("    			dataType: \"JSON\"\r\n");
      out.write("    		})\r\n");
      out.write("    		.done((res)=>{\r\n");
      out.write("    			alert(res.message);\r\n");
      out.write("    			\r\n");
      out.write("				if(res.result==\"success\"){\r\n");
      out.write("    			$(\"#idcheck\").val(\"Y\");\r\n");
      out.write("    			$(\"#user_id\").prop(\"readonly\", \"true\");					\r\n");
      out.write("    			$(\"#btnIdcheck\").prop(\"disabled\", \"true\");					\r\n");
      out.write("				} else{\r\n");
      out.write("				$(\"#user_id\").focus();\r\n");
      out.write("				}\r\n");
      out.write("    		})\r\n");
      out.write("    		.fail((res, status, error)=>{\r\n");
      out.write("    			console.log(status);\r\n");
      out.write("    			console.log(error);\r\n");
      out.write("    		});\r\n");
      out.write("    	})\r\n");
      out.write("    })\r\n");
      out.write("	\r\n");
      out.write("    function fnErrorCheck(){\r\n");
      out.write("    	if($(\"#user_id\").val().trim().length<6){\r\n");
      out.write("    		alert(\"아이디는 6자리 이상이어야 합니다.\");\r\n");
      out.write("    		$(\"#user_id\").focus();\r\n");
      out.write("    		return false;\r\n");
      out.write("    	}\r\n");
      out.write("    	\r\n");
      out.write("    	if($(\"#idcheck\").val()==\"N\"){\r\n");
      out.write("    		alert(\"아이디 중복체크를 하세요\");\r\n");
      out.write("    		$(\"#user_id\").focus();\r\n");
      out.write("			return false;    		\r\n");
      out.write("    	}\r\n");
      out.write("    	\r\n");
      out.write("    	if($(\"#password\").val().trim().length<4){\r\n");
      out.write("    		alert(\"비밀번호는 4자리 이상이어야 합니다.\");\r\n");
      out.write("    		$(\"#password\").focus();\r\n");
      out.write("    		return false;\r\n");
      out.write("    	}\r\n");
      out.write("    	if($(\"#password\").val()!=$(\"#password2\").val()){\r\n");
      out.write("    		alert(\"비밀번호 확인이 일치하지 않습니다.\");\r\n");
      out.write("    		$(\"#password2\").focus();\r\n");
      out.write("    		return false;\r\n");
      out.write("    	}\r\n");
      out.write("    	if($(\"#user_name\").val().trim().length<1){\r\n");
      out.write("    		alert(\"이름을 입력하세요.\");\r\n");
      out.write("    		$(\"#user_name\").focus();\r\n");
      out.write("    		return false;\r\n");
      out.write("    	}\r\n");
      out.write("    	if($(\"#email\").val().trim().length<1){\r\n");
      out.write("    		alert(\"이메일을 입력하세요.\");\r\n");
      out.write("    		$(\"#email\").focus();\r\n");
      out.write("    		return false;\r\n");
      out.write("    	}\r\n");
      out.write("    	\r\n");
      out.write("    	\r\n");
      out.write("    	return true;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
