/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-02-14 06:54:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kosa.myapp3.common.*;
import com.kosa.myapp3.board.*;

public final class board_005fwrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/board/../include/navbar.jsp", Long.valueOf(1675829143388L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.kosa.myapp3.common");
    _jspx_imports_packages.add("com.kosa.myapp3.board");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form id=\"myform\" name=\"myform\">\r\n");
      out.write("<!-- 메뉴 -->\r\n");
      out.write("\r\n");
      out.write("<!-- 메뉴 -->\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<!-- 한글 깨짐 방지 -->\r\n");

// 공통변수 CONTEXT 만들어 놓고 갖다 쓰기
String CONTEXT = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-sm navbar-light\" style=\"background-color: lavender\">\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<a class=\"navbar-brand\" href=\"");
      out.print(CONTEXT);
      out.write("\"> <img\r\n");
      out.write("			src=\"https://imjustcreative.com/wp-content/uploads/2015/11/Screenshot-2019-11-23-17.32.44.jpg\" alt=\"Avatar Logo\"\r\n");
      out.write("			style=\"width: 40px;\" class=\"rounded-pill\">\r\n");
      out.write("		</a>\r\n");
      out.write("\r\n");
      out.write("		<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("			data-bs-target=\"#collapsibleNavbar\">\r\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("		</button>\r\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"collapsibleNavbar\">\r\n");
      out.write("			<ul class=\"navbar-nav\">\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("					href=\"");
      out.print(CONTEXT);
      out.write("/board/list?pg=0\">List</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("					href=\"");
      out.print(CONTEXT);
      out.write("/board/write\">Write</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("					href=\"");
      out.print(CONTEXT);
      out.write("/member/write\">Sign up</a></li>\r\n");
      out.write("				<li class=\"nav-item dropdown\"><a\r\n");
      out.write("					class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\"\r\n");
      out.write("					data-bs-toggle=\"dropdown\">Gallery</a>\r\n");
      out.write("					<ul class=\"dropdown-menu\">\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"");
      out.print(CONTEXT);
      out.write("/gallery/list\">Gallery list</a></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"");
      out.print(CONTEXT);
      out.write("/gallery/write\">Gallery write</a></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"#\">A third link</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		");
if(session.getAttribute("user_id")==null||session.getAttribute("user_id").equals("")) {
      out.write("\r\n");
      out.write("			<ul class=\"navbar-nav justify-content-end\">\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("				<a class=\"nav-link\" href=\"");
      out.print(CONTEXT);
      out.write("/member/login\">로그인</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("				<a class=\"nav-link\" href=\"");
      out.print(CONTEXT);
      out.write("/member/write\">회원가입</a>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		");
} else {
      out.write("\r\n");
      out.write("			<ul class=\"navbar-nav justify-content-end\">\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("				<a class=\"nav-link\" href=\"#none\">");
      out.print(session.getAttribute("user_name") );
      out.write("</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("				<a class=\"nav-link\" href=\"#none\" onclick=\"goLogout()\">로그아웃</a>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		");
} 
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function goLogout() {\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url:\"");
      out.print(request.getContextPath());
      out.write("/member/logout\",\r\n");
      out.write("		method:\"POST\",\r\n");
      out.write("		dataType:\"JSON\"\r\n");
      out.write("	})\r\n");
      out.write("	.done(function (response){\r\n");
      out.write("		alert(response.message);\r\n");
      out.write("		if(response.result==\"success\"){\r\n");
      out.write("			location.href=\"");
      out.print(request.getContextPath());
      out.write("/\";\r\n");
      out.write("		}\r\n");
      out.write("	})\r\n");
      out.write("	.fail((response, status, error)=>{\r\n");
      out.write("		console.log(error);\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\r\n");

//		수정, 답글, 추가
//		if 문으로 상황에 따라 다르게 동작하게 하는 것보다는 똑같이 dto 객체를 만들어 보내는 것이 프로그램이 편하다
//		수정 - 수정할 글 정보 Dto
//		답글 - 원글에 대한 정보 Dto
//		추가 - 비어있는 Dto
	BoardDto dto = (BoardDto)request.getAttribute("boardDto");

	String mode = StringUtil.nullToValue(request.getParameter("mode"), "insert");
	String seq = StringUtil.nullToValue(request.getParameter("seq"), "-1");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<input type=\"hidden\" id=\"mode\" name=\"mode\" value=\"");
      out.print(mode );
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"seq\" name=\"seq\" value=\"");
      out.print(seq );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container mt-3\">\r\n");
      out.write("  <h3>게시판 글쓰기	</h3>\r\n");
      out.write("  \r\n");
      out.write("   <table class=\"table\">\r\n");
      out.write("   	<colgroup>\r\n");
      out.write("   		<col width=\"30%\">\r\n");
      out.write("   		<col width=\"*\">\r\n");
      out.write("   	</colgroup>\r\n");
      out.write("    <tbody>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th>제목</th>\r\n");
      out.write("        <td>\r\n");
      out.write("        	 <div class=\"input-group\">\r\n");
      out.write("			    <input type=\"text\" class=\"form-control\" placeholder=\"제목을 입력하세요\"\r\n");
      out.write("			    name=\"title\" id=\"title\" value=\"");
      out.print(dto.getTitle());
      out.write("\">\r\n");
      out.write("			 </div>\r\n");
      out.write("        </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th>작성자</th>\r\n");
      out.write("        <td>\r\n");
      out.write("        	 <div class=\"input-group\">\r\n");
      out.write("			    <input type=\"hidden\" class=\"form-control\" placeholder=\"이름을 입력하세요\"\r\n");
      out.write("			    name=\"userid\" id=\"userid\" value=\"");
      out.print(session.getAttribute("user_id"));
      out.write("\">\r\n");
      out.write("			    <input type=\"text\" class=\"form-control\" placeholder=\"이름을 입력하세요\"\r\n");
      out.write("			    name=\"username\" id=\"username\" value=\"");
      out.print(session.getAttribute("user_name"));
      out.write("\" readonly>\r\n");
      out.write("			 </div>\r\n");
      out.write("        </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th>내용</th>\r\n");
      out.write("        <td>\r\n");
      out.write("        	 <div class=\"input-group\">\r\n");
      out.write("			    <textarea class=\"form-control\" placeholder=\"내용 입력하세요\"\r\n");
      out.write("			    name=\"contents\" id=\"contents\" rows=\"5\">");
      out.print(dto.getContents() );
      out.write("</textarea>\r\n");
      out.write("			 </div>\r\n");
      out.write("        </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th>이미지 첨부</th>\r\n");
      out.write("        <td>\r\n");
      out.write("        	 ");
if(!mode.equals("modify")){ 
      out.write("\r\n");
      out.write("	        	 <div class=\"input-group\">\r\n");
      out.write("				    <input class=\"form-control\" type=\"file\" placeholder=\"이미지 파일을 첨부하세요\"\r\n");
      out.write("				    name=\"file1\" id=\"file1\">\r\n");
      out.write("				 </div>\r\n");
      out.write("			 ");
}else{ 
      out.write("\r\n");
      out.write("	        	 <div class=\"input-group\">\r\n");
      out.write("				    <input class=\"form-control\" type=\"file\" placeholder=\"이미지 파일을 첨부하세요\" name=\"file1\" id=\"file1\" style=\"display: none\">\r\n");
      out.write("				    <input type=\"checkbox\" id=\"del1\" onclick=\"goChange('1')\" value=\"1\">\r\n");
      out.write("				    <input type=\"text\" name=\"old_name\" id=\"old_name1\" value=\"");
      out.print(dto.getFilename1());
      out.write("\">\r\n");
      out.write("				 </div>\r\n");
      out.write("			");
} 
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			");
if(!mode.equals("modify")){ 
      out.write("\r\n");
      out.write("	        	 <div class=\"input-group\">\r\n");
      out.write("				    <input class=\"form-control\" type=\"file\" placeholder=\"이미지 파일을 첨부하세요\"\r\n");
      out.write("				    name=\"file2\" id=\"file2\">\r\n");
      out.write("				 </div> \r\n");
      out.write("			 ");
}else{ 
      out.write("\r\n");
      out.write("				 <div class=\"input-group\">\r\n");
      out.write("				    <input class=\"form-control\" type=\"file\" placeholder=\"이미지 파일을 첨부하세요\"\r\n");
      out.write("				    name=\"file2\" id=\"file2\" style=\"display: none\">\r\n");
      out.write("				    <input type=\"checkbox\" id=\"del2\" onclick=\"goChange('2')\" value=\"2\">\r\n");
      out.write("				    <input type=\"text\" name=\"old_name\" id=\"old_name2\" value=\"");
      out.print(dto.getFilename2());
      out.write("\">\r\n");
      out.write("				 </div>\r\n");
      out.write("			");
} 
      out.write("		\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			");
if(!mode.equals("modify")){ 
      out.write("	 \r\n");
      out.write("	        	 <div class=\"input-group\">\r\n");
      out.write("				    <input class=\"form-control\" type=\"file\" placeholder=\"이미지 파일을 첨부하세요\"\r\n");
      out.write("				    name=\"file3\" id=\"file3\">\r\n");
      out.write("				 </div>\r\n");
      out.write("			  ");
}else{ 
      out.write("\r\n");
      out.write("				 <div class=\"input-group\">\r\n");
      out.write("				    <input class=\"form-control\" type=\"file\" placeholder=\"이미지 파일을 첨부하세요\"\r\n");
      out.write("				    name=\"file3\" id=\"file3\" style=\"display: none\">\r\n");
      out.write("				    <input type=\"checkbox\" id=\"del3\" onclick=\"goChange('3')\" value=\"3\">\r\n");
      out.write("				    <input type=\"text\" name=\"old_name\" id=\"old_name3\" value=\"");
      out.print(dto.getFilename3());
      out.write("\">\r\n");
      out.write("				 </div>\r\n");
      out.write("			");
} 
      out.write("		\r\n");
      out.write("        </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("    </tbody>\r\n");
      out.write("  </table>\r\n");
      out.write(" </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <div class=\"container\" style=\"text-align:right\">\r\n");
      out.write("	<button type=\"button\" class=\"btn\" style=\"background-color: lavender\" id=\"btnSave\">글쓰기</button>\r\n");
      out.write(" </div>\r\n");
      out.write("\r\n");
      out.write("</form>  \r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("$(()=>{\r\n");
      out.write("	$(\"#btnSave\").click(goSend); \r\n");
      out.write("	//goSend : 함수 주소만 전달(괄호 없어야함)\r\n");
      out.write("	\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("function goChange(id){\r\n");
      out.write("	if(document.getElementById(\"del\"+id).checked){\r\n");
      out.write("		/* 체크박스 누르면 파일 선택 가능하도록 */\r\n");
      out.write("		document.getElementById(\"file\"+id).style.display=\"block\";\r\n");
      out.write("	} else{\r\n");
      out.write("		document.getElementById(\"file\"+id).style.display=\"none\";\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function goSend(){\r\n");
      out.write("	//자바스크립트 ajax로 파일 전송 시 FormData(폼 객체) 함수를 이용해 form에 있는 데이터들을 직렬화 한다.\r\n");
      out.write("	//document.폼이름\r\n");
      out.write("	//jquery의 경우 $(\"#폼아이디\")[0] : 인덱스 생략 불가\r\n");
      out.write("	let frmData = new FormData(document.myform);\r\n");
      out.write("	for(key of frmData.keys()){\r\n");
      out.write("		console.log(key); \r\n");
      out.write("		//키 출력\r\n");
      out.write("		console.log(frmData.get(key)); \r\n");
      out.write("		//값 출력\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	let url =\"\";\r\n");
      out.write("	console.log(frmData);\r\n");
      out.write("	\r\n");
      out.write("	if($(\"#mode\").val()==\"insert\"){		\r\n");
      out.write("	 	url = \"");
      out.print(request.getContextPath());
      out.write("/board/save\"\r\n");
      out.write("	} else if($(\"#mode\").val()==\"reply\"){\r\n");
      out.write("		url = \"");
      out.print(request.getContextPath());
      out.write("/board/reply_save\";\r\n");
      out.write("	} else{\r\n");
      out.write("		url = \"");
      out.print(request.getContextPath());
      out.write("/board/modify_save\";\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	console.log($(\"#mode\").val(), url);\r\n");
      out.write("	\r\n");
      out.write("	if($(\"#mode\").val()==\"modify\"){\r\n");
      out.write("		for(i=1; i<=3; i++){\r\n");
      out.write("			/* check 안 된 경우만 추가한다. */\r\n");
      out.write("			if(!document.getElementById(\"del\"+i).checked){\r\n");
      out.write("				frmData.append(\"del\", \"\");\r\n");
      out.write("			} else{\r\n");
      out.write("				frmData.append(\"del\", $(\"#del\"+i).val());\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("		let file = frmData.get(\"file1\");\r\n");
      out.write("		console.log(file.type);	\r\n");
      out.write("		console.log(file.size);	\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url:url,\r\n");
      out.write("		data:frmData,\r\n");
      out.write("		dataType:\"json\",\r\n");
      out.write("		processData:false,\r\n");
      out.write("		contentType:false,\r\n");
      out.write("		enctype:\"multipart/form-data\",\r\n");
      out.write("		timeout:600000,\r\n");
      out.write("		type:\"POST\"\r\n");
      out.write("	})\r\n");
      out.write("	.done(function (res){\r\n");
      out.write("		alert(res.message);\r\n");
      out.write("		location.href=\"");
      out.print(request.getContextPath());
      out.write("/board/list\";\r\n");
      out.write("	})\r\n");
      out.write("	.fail(function (res, status, error){\r\n");
      out.write("		console.log(status);\r\n");
      out.write("		console.log(error);\r\n");
      out.write("	})  \r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
