/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-02-13 01:02:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kosa.myapp3.common.StringUtil;
import com.kosa.myapp3.board.*;
import com.kosa.myapp3.common.Pager;
import java.util.*;

public final class board_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/board/../include/navbar.jsp", Long.valueOf(1675829143388L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.kosa.myapp3.board");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kosa.myapp3.common.StringUtil");
    _jspx_imports_classes.add("com.kosa.myapp3.common.Pager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js\"></script>  \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	String pg =StringUtil.nullToValue(request.getParameter("pg"), "0");

      out.write("\r\n");
      out.write("<form id=\"myform\" name=\"myform\">\r\n");
      out.write("<input type=\"hidden\" name=\"pg\" id=\"pg\" value=\"");
      out.print(pg);
      out.write("\">\r\n");
      out.write("<!-- 메뉴 -->\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("<!-- 메뉴 -->\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<!-- 한글 깨짐 방지 -->\r\n");

// 공통변수 CONTEXT 만들어 놓고 갖다 쓰기
String CONTEXT = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-sm navbar-light\" style=\"background-color: lavender\">\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<a class=\"navbar-brand\" href=\"");
      out.print(CONTEXT);
      out.write("\"> <img\r\n");
      out.write("			src=\"https://imjustcreative.com/wp-content/uploads/2015/11/Screenshot-2019-11-23-17.32.44.jpg\" alt=\"Avatar Logo\"\r\n");
      out.write("			style=\"width: 40px;\" class=\"rounded-pill\">\r\n");
      out.write("		</a>\r\n");
      out.write("\r\n");
      out.write("		<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("			data-bs-target=\"#collapsibleNavbar\">\r\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("		</button>\r\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"collapsibleNavbar\">\r\n");
      out.write("			<ul class=\"navbar-nav\">\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("					href=\"");
      out.print(CONTEXT);
      out.write("/board/list?pg=0\">List</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("					href=\"");
      out.print(CONTEXT);
      out.write("/board/write\">Write</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("					href=\"");
      out.print(CONTEXT);
      out.write("/member/write\">Sign up</a></li>\r\n");
      out.write("				<li class=\"nav-item dropdown\"><a\r\n");
      out.write("					class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\"\r\n");
      out.write("					data-bs-toggle=\"dropdown\">Gallery</a>\r\n");
      out.write("					<ul class=\"dropdown-menu\">\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"");
      out.print(CONTEXT);
      out.write("/gallery/list\">Gallery list</a></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"");
      out.print(CONTEXT);
      out.write("/gallery/write\">Gallery write</a></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"#\">A third link</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		");
if(session.getAttribute("user_id")==null||session.getAttribute("user_id").equals("")) {
      out.write("\r\n");
      out.write("			<ul class=\"navbar-nav justify-content-end\">\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("				<a class=\"nav-link\" href=\"");
      out.print(CONTEXT);
      out.write("/member/login\">로그인</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("				<a class=\"nav-link\" href=\"");
      out.print(CONTEXT);
      out.write("/member/write\">회원가입</a>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		");
} else {
      out.write("\r\n");
      out.write("			<ul class=\"navbar-nav justify-content-end\">\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("				<a class=\"nav-link\" href=\"#none\">");
      out.print(session.getAttribute("user_name") );
      out.write("</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("				<a class=\"nav-link\" href=\"#none\" onclick=\"goLogout()\">로그아웃</a>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		");
} 
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function goLogout() {\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url:\"");
      out.print(request.getContextPath());
      out.write("/member/logout\",\r\n");
      out.write("		method:\"POST\",\r\n");
      out.write("		dataType:\"JSON\"\r\n");
      out.write("	})\r\n");
      out.write("	.done(function (response){\r\n");
      out.write("		alert(response.message);\r\n");
      out.write("		if(response.result==\"success\"){\r\n");
      out.write("			location.href=\"");
      out.print(request.getContextPath());
      out.write("/\";\r\n");
      out.write("		}\r\n");
      out.write("	})\r\n");
      out.write("	.fail((response, status, error)=>{\r\n");
      out.write("		console.log(error);\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container mt-3\">\r\n");
      out.write("  <h3>Navbar With Dropdown</h3>\r\n");
      out.write("  <p>This example adds a dropdown menu in the navbar.</p>\r\n");
      out.write("  \r\n");
      out.write("   <div class=\"input-group mt-3 mb-3\">\r\n");
      out.write("	  <button style=\"background-color: lavender; border-radius: 10px 10px 10px 10px / 10px 10px 10px 10px; color: black\" type=\"button\" class=\"btn dropdown-toggle\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("	    Dropdown button\r\n");
      out.write("	  </button>\r\n");
      out.write("	  <ul class=\"dropdown-menu\">\r\n");
      out.write("	    <li><a class=\"dropdown-item\" href=\"#\">Link 1</a></li>\r\n");
      out.write("	    <li><a class=\"dropdown-item\" href=\"#\">Link 2</a></li>\r\n");
      out.write("	    <li><a class=\"dropdown-item\" href=\"#\">Link 3</a></li>\r\n");
      out.write("	  </ul>\r\n");
      out.write("	  &nbsp;<input type=\"text\" class=\"form-control\" placeholder=\"Username\">&nbsp;\r\n");
      out.write("	  <div class=\"input-group-append\">\r\n");
      out.write("	  	<button style=\"background-color: lavender; border-radius: 10px 10px 10px 10px / 10px 10px 10px 10px; color: black\" class=\"btn\" type=\"button\" >GO</button>\r\n");
      out.write("	  </div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	");

	List<BoardDto> list = (List<BoardDto>)request.getAttribute("boardList");
	int totalCnt = (Integer)request.getAttribute("totalCnt");
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("   <table class=\"table\">\r\n");
      out.write("   <colgroup>\r\n");
      out.write("   <col style=\"width: 10%\">\r\n");
      out.write("   <col style=\"width: *\">\r\n");
      out.write("   <col style=\"width: 15%\">\r\n");
      out.write("   <col style=\"width: 15%\">\r\n");
      out.write("   <col style=\"width: 10%\">\r\n");
      out.write("   </colgroup>\r\n");
      out.write("    <thead class=\"table\" style=\"background-color: lavender\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th>번호</th>\r\n");
      out.write("        <th>제목</th>\r\n");
      out.write("        <th>작성자</th>\r\n");
      out.write("        <th>작성일</th>\r\n");
      out.write("        <th>조회수</th>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </thead>\r\n");
      out.write("    <tbody>\r\n");
      out.write("    ");
for(int i=0; i<list.size(); i++){
    	BoardDto dto = list.get(i);
    	String reply="";
    	for(int j=0; j<dto.getDepth(); j++){
    		reply = reply+"&nbsp;&nbsp;&nbsp;";
    	}
    	if(!reply.equals("")){
    		reply=reply+"re:";
    	}
    
      out.write("\r\n");
      out.write("      <tr>\r\n");
      out.write("        \r\n");
      out.write("       ");
if(dto.getDelyn().equals("N")){
      out.write("\r\n");
      out.write("	       ");
if(dto.getDelyn2().equals("N")) {
      out.write("\r\n");
      out.write("			    <td>");
      out.print(totalCnt - dto.getNum() +1 );
      out.write("</td>\r\n");
      out.write("	        	<td>");
      out.print(reply);
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/board/view?seq=");
      out.print(dto.getSeq());
      out.write('"');
      out.write('>');
      out.print(dto.getTitle());
      out.write("</a></td>\r\n");
      out.write("		        <td>");
      out.print(dto.getUserid());
      out.write("</td>\r\n");
      out.write("	    	    <td>");
      out.print(dto.getRegdate());
      out.write("</td>\r\n");
      out.write("	        	<td>");
      out.print(dto.getHit());
      out.write("</td>\r\n");
      out.write("	        ");
}else{
      out.write("\r\n");
      out.write("	        	<td colspan=\"9\">삭제된 글:");
      out.print(dto.getTitle() );
      out.write("</td>\r\n");
      out.write("	        ");
} 
      out.write("	\r\n");
      out.write("        ");
}
      out.write("\r\n");
      out.write("      </tr>\r\n");
      out.write("      ");
} 
      out.write("\r\n");
      out.write("    </tbody>\r\n");
      out.write("  </table>\r\n");
      out.write(" </div>\r\n");
      out.write(" <div class=\"container\" style=\"text-align:right\">\r\n");
      out.write("  ");
      out.print(Pager.makeTag(request, totalCnt, 10) );
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write(" <div class=\"container\" style=\"text-align:right\">\r\n");
      out.write("	<button type=\"button\" class=\"btn\" style=\"background-color: lavender; color: black\" onclick=\"goWrite()\">글쓰기</button>\r\n");
      out.write(" </div>\r\n");
      out.write("\r\n");
      out.write(" </form> \r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function goPage(pg) {\r\n");
      out.write("	//jquery 방식\r\n");
      out.write("	//alert(pg); //-> 디버깅용\r\n");
      out.write("	$(\"#pg\").val(pg);\r\n");
      out.write("	$(\"#myform\").prop(\"action\", \"");
      out.print(request.getContextPath());
      out.write("/board/list\");\r\n");
      out.write("	$(\"#myform\").submit();\r\n");
      out.write("}\r\n");
      out.write("function goWrite() {\r\n");
      out.write("	var frm = document.myform;\r\n");
      out.write("	frm.action = \"");
      out.print(request.getContextPath());
      out.write("/board/write\";\r\n");
      out.write("	frm.method=\"post\";\r\n");
      out.write("	frm.submit();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
